### PR TITLE
Add Code of Conduct

### PR DESCRIPTION
**Pull request by abelsiqueira**
**Changes**
- Create a CODE_OF_CONDUCT from https://www.contributor-covenant.org/version/2/1/code_of_conduct/

**Ref**
- #20 

**Verify**
Verify text online

**Blocked**
- ~~We need a maintainer contact. @benvanwerkhoven @bouweandela @isazi~~ Decision moved to #49 
- ~~#42 needs to be merged first~~

### CODE REVIEW

**Review by fdiblen — APPROVED** [review]
Thanks @abelsiqueira :game_die:

**Comment by abelsiqueira** [comment]
Thanks for the review

**Comment by bouweandela** [comment]
You forgot to add the contact in case of trouble...

**Comment by abelsiqueira** [comment]
#49 is the decision around the contact.

**Pull request merged**
